Android OAuth2 라이브러리 PR
ridi/android-oauth2 pull request #1
Opened 2018-06-18 07:39 UTC by RidiSangHoon

Android OAuth2 라이브러리 PR 입니다.

OAuth 라이브러리에 관한 자세한 플로우는 https://ridicorp.atlassian.net/wiki/spaces/DevSpace/pages/582058299/2018-05+- 
의 인증세션 부분에서 확인하실 수 있습니다.

라이브러리 테스트를 위해 임시적으로 android-oauth2 라이브러리를 jitpack이 아닌 프로젝트 형식으로 gradle에 추가하였습니다.

2018-06-19 05:15 UTC, InyoungAum requested changes
대부분의 파일 끝에 개행문자가 필요해보입니다.

2018-06-19 05:15 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/androidoauth2/ApiManager.kt
> +                    if (it.split("=", ";")[0] == "ridi-at" || it.split("=", ";")[0] == "ridi-rt") {
`it.split("=", ";")`이 여러번 나오는데, 변수로 따로 빼는 것이 좋아 보입니다.

2018-06-19 05:15 UTC, InyoungAum commented on .idea/dictionaries/leesanghoon.xml
> -<component name="ProjectDictionaryState">
`.idea`하위 항목들은  gitignore에 추가하는게 좋아보입니다.

2018-06-19 05:15 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/androidoauth2/RidiOAuth2.kt
> +                                it.onError(Throwable(response.headers().get("Location")))
`response.headers().get("Location")`을 변수로 빼는것이 좋아보입니다.

2018-06-19 05:15 UTC, InyoungAum commented on app/src/main/java/com/ridi/oauth2/MainActivity.kt
> +                    Log.e(javaClass.name, "Received => $it")
error가 아니므로 e보다는 다른것을 사용하는게 좋을것 같습니다.

2018-06-19 05:15 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/androidoauth2/ApiManager.kt
> +    fun ridiToken(@Header("Cookie") authToken: String,
`ridiToken` 네이밍을 구체적으로 하는것이 좋아보입니다.

2018-06-20 03:05 UTC, RidiSangHoon commented
어제 @kgwangrae 님께서 구두로 말씀해주신 PR 리뷰내용들 적용하고 다시 열겠습니다.

2018-06-20 03:10 UTC, freekering commented
@RidiSangHoon @kgwangrae 구두로 전달된 내용을 기록으로 남겨주세요.

https://github.com/ridi/style-guide#%EC%BD%94%EB%93%9C-%EB%A6%AC%EB%B7%B0-%EC%9B%90%EC%B9%99
`가능한 모든 수단을 사용하여 토론하되 결론은 반드시 기록해야 합니다.`

2018-06-20 06:08 UTC, RidiSangHoon commented
@kgwangrae 님께 구두로 전달받은 내용입니다.
> 1. `RidiOAuth2`에서 파일을 읽거나 쓸 때, rbhelper 라이브러리를 참조할 수 있도록 수정
> 2. 어플리케이션에서 라이브러리에 파일이 저장되는 위치를 지정하도록 수정
> 3. 어플리케이션에서 `RidiOAuth2`의 cookies에 직접 접근하지 않도록 수정
> 4. `RidiOAuth2`가 싱글톤인 것은 바람직하지 못하다. (싱글톤으로 만들어서 쓸지 여부는 어플리케이션에서 결정)
> 5. 리디 스타일 가이드(https://github.com/ridi/style-guide/tree/master/Android) 에 아직 부합하지 못한 부분들 수정

2018-06-29 09:22 UTC, RidiSangHoon commented
@kgwangrae @InyoungAum 
리뷰 내용들 적용하고 다시 PR 열었습니다~!

2018-06-29 10:13 UTC, InyoungAum requested changes

2018-06-29 10:13 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/oauth2/ApiManager.kt
> +            if (cookie[0] == "ridi-at" || cookie[0] == "ridi-rt") {
`ridi-at`, `ridi-rt`는 사용하는곳이 많아 따로 상수로 빼도 좋을 것 같습니다.

2018-06-29 10:13 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +            return Observable.create(ObservableOnSubscribe<JWT> { emitter ->
```
return Observable.create(ObservableOnSubscribe<JWT> { 
    ...
}).subscribeOn(AndroidSchedulers.mainThread())
```
으로 묶고 안에 조건문들을 넣으면 더 깔끔할것 같습니다.

2018-06-29 10:13 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +    fun setDev() {
setDev보다는 setDevMode가 좋을 것 같습니다. 
추가로 boolean 변수를 두고 BASE_URL에 if문을 넣는 것은 어떨까요?

2018-06-29 10:13 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        tokenFile = File(tokenFilePath)
`setTokenFilePath`를 통해 TokenFile을 생성하는것 까진 유추하기 힘들어 보입니다.

2018-06-29 10:13 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +                    manager.create().requestAuthorization(clientId, "code", redirectUri)
`requestAuthorization`등의 함수로 빼도 좋을 것 같습니다.

2018-06-29 10:13 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +                    manager.create().refreshAccessToken(getAccessToken(), getRefreshToken())
`refreshAccessToken`등의 함수로 빼도 좋을 것 같습니다.

2018-06-29 12:27 UTC, Linus1019 commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        if (rawAccessToken == "") {
빈 문자열 비교는 isEmpty함수를 써도 괜찮지 않을까요? 
수정 하신다면 다른 부분들도 적용 부탁드립니다.

2018-06-29 12:27 UTC, Linus1019 commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +                                if (response.code() == 302) {
쓰는 곳은 두 곳 뿐이지만 리퀘스트 코드에 대한 정의를 해주는 것은 어떤가요?

2018-06-29 12:27 UTC, Linus1019 commented on app/src/main/res/layout/activity_main.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
RelativeLayout을 제거하고 밑에 LinearLayout을 최상위로 변경해도 될 것 같습니다.

2018-07-04 07:13 UTC, RidiSangHoon commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +    fun setDev() {
좋은 의견 감사합니다. 저도 처음에는 그렇게 작성하였는데 boolean 변수를 두게 된다면 해당 변수가 개발/실서버 세팅하는 기능외엔 하는 것이 없고 변수 없이 개발모드일때에만 BASE_URL 세팅만 해줘도 될 것 같아 삭제하였습니다. 
`setDev`보다는 `setDevMode`가 저도 좋은것 같아 네이밍은 우선 수정하겠습니다~!

2018-07-04 08:06 UTC, kgwangrae requested changes

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        internal fun JSONObject.parseCookie(cookieString: String) {
내용이 같은 parseCookie가 ApiManager에도 중복으로 있습니다.

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        var instance = RidiOAuth2()
여전히 라이브러리에서 Singleton을 강제하고 있습니다.

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        internal lateinit var tokenFile: File
`tokenFilePath`와 달리 companion object에 위치해있어서 적절하지 않은 것 같습니다. (더불어서 path로부터 쉽게 구할 수 있는 부분이라 저장하지 않아도 무방할 것 같기는 하네요)

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        manager.cookies = HashSet()
세션ID 설정 시 기존 쿠키가 모두 초기화되어야 하는 것인가요?

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +    fun setClientId(clientId: String) {
불필요한 function인 것 같습니다. 특별히 setter만 public이고 getter는 private이어야 할 이유가 없다면요.

다른 function들도 같이 검토 부탁드립니다.

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +    private var rawAccessToken = ""
무언가 '없는' 상태에 `null` 대신 empty String을 사용하신 이유가 있나요?

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +    fun getRefreshToken(): String {
파일에 있는 토큰을 읽어오기만 하는 두 함수 (`get Access/Refresh Token`) 와 토큰 파일이 없다면 API 호출을 통해 토큰을 가져오는 동작도 포함하는 `getOAuthToken` 함수 각각의 이름만으로는 동작 상의 차이를 구분할 수 없을 것 같습니다.

2018-07-04 08:06 UTC, kgwangrae commented on app/build.gradle
> +    //    implementation 'com.github.ridi:android-oauth2:1.0.0'
불필요한 주석이 남아있습니다.

2018-07-04 08:06 UTC, kgwangrae commented on build.gradle
>      ext.kotlin_version = '1.2.20'
코틀린 버전 업데이트가 필요합니다.

2018-07-04 08:06 UTC, kgwangrae commented on app/build.gradle
> +    implementation 'com.android.support:multidex:1.0.3'
가능하다면 디펜던시 정리 후에 multidex를 비활성화하는 것이 좋을 것 같습니다. (테스트 앱 뿐만 아니라 라이브러리에도 multidex가 켜져있습니다.)

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/ApiManager.kt
> +        var cookies = HashSet<String>()
사용처인 `CookieInterceptor`에서 가지고 있는 것이 바람직할 것 같습니다.

2018-07-04 08:06 UTC, kgwangrae commented on android-oauth2/build.gradle
> +    api 'com.squareup.okhttp3:mockwebserver:3.7.0'
api 대신에 androidTestImplementation이 되어야 할 것 같네요.

2018-07-05 09:22 UTC, RidiSangHoon commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        manager.cookies = HashSet()
음.. 이전에 설정되어있던 쿠키값들이 결과값에 영향을 주면 안되므로 초기화하였습니다~

2018-07-05 10:30 UTC, RidiSangHoon commented
@InyoungAum @kgwangrae @Linus1019 
리뷰내용들 모두 적용하였습니다. 리뷰 부탁드립니다~!

2018-07-06 01:09 UTC, InyoungAum requested changes

2018-07-06 01:09 UTC, InyoungAum commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        val manager = ApiManager()
ApiManager를 매번 생성하는 이유가 있나요? 미리 만들어 놔도 괜찮을 것 같습니다.

2018-07-06 01:59 UTC, freekering commented
@RidiSangHoon Kotlin으로만 이루어진 프로젝트라면 src 디렉토리를 `java`가 아닌 `kotlin`으로 해주세요.
그 밖에 좀 불필요한 군더더기들이(.gitignore의 fastlane 관련된 line이라던지..)이 좀 보이는데 본 프로젝트는 라이브러리 프로젝트이기 때문에 다른 라이브러리 프로젝트를 참고했었어야 하는데 리디북스앱 프로젝트를 참고하는바람에 그렇게 된 것 같습니다. 그런 부분들 정리를 좀 해주세요.
어쨌든 지금 상훈님 손으로 만들어진 모든 부분에 대해서 그게 왜 있는지 다 이유를 알고 있어야 합니다.

2018-07-06 08:47 UTC, kgwangrae commented on android-oauth2/src/main/java/com/ridi/oauth2/RidiOAuth2.kt
> +        manager.cookies = HashSet()
@RidiSangHoon  음 그것보다는 setSessionId를 했을 때 나머지 쿠키가 전부 날아가는 것이 예측 가능한 동작인지에 대한 질문입니다. (서로 직접적인 연관성을 생각하기 어렵지 않을까요)

2018-07-09 10:25 UTC, kgwangrae commented
@RidiSangHoon 
- travis script에 ktlint만 포함되어있는 상태라 수정 부탁드립니다.
- ( 2192101 commit 기준으로 ) Android Studio에서 RidiOAuth2Test 파일에 오류가 있는 것으로 표시됩니다. 확인 부탁드립니다.

2018-07-12 06:03 UTC, freekering commented on demoapp/src/main/kotlin/com/ridi/demoapp/MainActivity.kt
> +            Thread().run {
별도 Thread에서 실행하는 걸 의도한 거라면.. 심각하게 잘못 됐습니다.

2018-07-16 02:05 UTC, Linus1019 approved these changes

2018-07-16 02:27 UTC, InyoungAum requested changes

2018-07-16 02:27 UTC, InyoungAum commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        return manager.service!!.refreshAccessToken(rawAccessToken!!, refreshToken!!)
`return`은 필요 없어 보입니다.

2018-07-16 06:58 UTC, InyoungAum approved these changes

2018-07-17 06:15 UTC, freekering commented
@RidiSangHoon 

1. 로컬에 설치해서 테스트해보니 maven repository의 group id와 artifact id는 여전히 각각 `android-oauth2`로 잡히고 있습니다. 의도한게 아니라면 적절히 수정되어야 합니다.
(maven repository 형태로 배포되는 건 demoapp을 제외한 library 부분 뿐이므로 이와 관련된 설정도 그쪽에만 있으면 됩니다)

2. Library module 에서는 (특별한 경우가 아니라면) build type을 나누는게 의미가 없습니다. 따라서 `consumerProguardFiles` 는 그냥 `defaultConfig`에만 있으면 되고 `minifyEnabled` 같은 것도 앱을 빌드하는게 아니기 때문에 아무 의미가 없습니다. (그냥 단순하게 다른 Library project만 잘 참고하면 아무 문제가 없는데 자꾸 자의적으로 바뀌는 현상이 계속 왜 반복되는지 잘 모르겠네요)

3. Library module에 포함된 `proguard-rules.pro` 내용은 전부 필요한 건가요? (없으면 문제가 된다는 사실이 테스트된 것인지)

2018-07-17 09:00 UTC, kgwangrae requested changes

2018-07-17 09:00 UTC, kgwangrae commented on demoapp/src/main/kotlin/com/ridi/demoapp/MainActivity.kt
> +                Log.e(javaClass.name, "Error => $it")
adb 연결 없이도 간단하게라도 (Toast / Dialog 등) 결과를 눈으로 볼 수 있으면 좋을 것 같습니다

2018-07-17 09:00 UTC, kgwangrae commented on demoapp/src/main/kotlin/com/ridi/demoapp/WebViewActivity.kt
> +    private val BASE_URL = "https://$DEV_HOST"
외부 접속이 가능한 `REAL_HOST`가 기본값인 것이 좋을 것 같습니다.

2018-07-17 09:00 UTC, kgwangrae commented on demoapp/build.gradle
> +    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
2.0.2로 업데이트가 가능합니다.

2018-07-17 09:00 UTC, kgwangrae commented on demoapp/src/main/kotlin/com/ridi/demoapp/MainActivity.kt
> +        internal var tokenManager = TokenManager()
굳이 companion에 있을 필요는 없을 것 같습니다.

2018-07-17 09:00 UTC, kgwangrae commented on demoapp/build.gradle
> +    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
https://github.com/ReactiveX/RxAndroid README에 아래와 같은 설명이 있네요. 참고 부탁드립니다.

```
// Because RxAndroid releases are few and far between, it is recommended you also
// explicitly depend on RxJava's latest version for bug fixes and new features.
// (see https://github.com/ReactiveX/RxJava/releases for latest 2.x.x version)
implementation 'io.reactivex.rxjava2:rxjava:2.x.x'
```

2018-07-17 09:00 UTC, kgwangrae commented on demoapp/build.gradle
> +    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
라이브러리의 build.gradle도 같이 확인해주세요~

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
kotlin-reflect가 필요한가요?

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                    .setResponseCode(HttpURLConnection.HTTP_MOVED_TEMP)
line 59와 동일한 방식을 사용하는 것이 좋을 것 같습니다. (HTTP_OK, HTTP_MOVED_TEMP 사용 또는 200, 302 사용)

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +import junit.framework.Assert.assertEquals
일관성 측면에서 `org.junit.Assert`를 사용하는 것이 좋을 것 같습니다.

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +        } catch (e: Exception) {
굳이 try-catch로 감싸지 않아도 될 것 같습니다.

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                    .addHeader("Set-Cookie", rtCookies)
하나의 `Set-Cookie`에 at, rt가 같이 담기는 것이 맞을 것 같습니다.

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/CookieInterceptor.kt
> +                cookies.add(it)
it 보다는 명시적인 변수명을 사용해주세요.

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +    private var manager = ApiManager()
`TokenManger` 내부에 `manager`라는 이름이 있어서 혼동을 유발하는 것 같습니다. (`apiManager` 등이 더 나을 것 같습니다.)

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +    private fun getSavedJSON() = JSONObject(readJSONFile())
`readJSONFile`은 굳이 별도 function일 필요가 없어보입니다. (구현이 간단하고, 호출하는 곳이 이곳 뿐입니다.)

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        refreshToken = null
`parsedAccessToken`도 지워야하지 않나요?

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +    var clientId: String? = null
configuration에 해당하는 값들 (clientId, tokenFile, useDevMode) 변경시에도 `clearSavedTokens`가 호출되어야 할 것 같습니다. (한편 `clearSavedTokens`의 경우 명칭 상으로는 저장된 토큰을 지우는 것 같지만 실제 동작은 그렇지 않아서 헷갈리네요.)

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.onComplete()
http://reactivex.io/documentation/contract.html 에 위배됩니다. 다른 부분도 확인 부탁드립니다. (`onError`이후 `onComplete`가 불림)

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        }).subscribeOn(AndroidSchedulers.mainThread())
스케줄러를 지정해주지 않아도 무방할 것 같습니다.

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.onError(IllegalStateException())
`t`를 전달하는 것이 좋을 것 같습니다.

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                            emitter.onError(MalformedURLException())
상황에 맞지않는 Exception인 것 같습니다. (line 143도 같이 확인 부탁드립니다.)

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                            emitter.onError(MalformedURLException())
로그인이 해제된 경우 올바르게 동작하나요?

2018-07-17 09:00 UTC, kgwangrae commented on android-oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                val rtCookies = "$COOKIE_KEY_RIDI_RT=$RIDI_RT;"
`/ridi/token`의 경우 응답 코드가 200이라서 `/ridi/authorize` (302)와 다릅니다.

2018-07-17 09:38 UTC, RidiSangHoon commented on android-oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                    .addHeader("Set-Cookie", rtCookies)
@kgwangrae 
Cookie Interceptor에서 쿠키값을 받아올때, ridi-at, ridi-rt 값이 서로 다른 Cookie Header에 담겨있어서 Test 부분에서도 at,rt 각각 넘겨주었습니다~

2018-07-19 00:54 UTC, DavinAhn commented on demoapp/src/main/kotlin/com/ridi/demoapp/WebViewActivity.kt
> +    private val BASE_URL = "https://$DEV_HOST"
@RidiSangHoon 
테섭으로 돌리거나 클라이언트 아이디를 지워주세요.
계정팀에서 실섭용 아이디는 노출되지 않기를 오구했었습니다.

2018-07-19 09:28 UTC, RidiSangHoon commented on android-oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                            emitter.onError(MalformedURLException())
로그인이 해제된 경우 `ResponseCodeException` 가 호출됩니다.

2018-07-19 09:29 UTC, RidiSangHoon commented
@kgwangrae @DavinAhn 
코멘트 내용 적용하였습니다. 리뷰 부탁드립니다~!

2018-07-20 07:32 UTC, DavinAhn approved these changes

2018-07-20 07:55 UTC, kgwangrae requested changes

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +class UnExpectedRedirectUriException(override var message: String) : RuntimeException(message)
unexpected는 하나의 단어이므로 Unexpected~... 가 되어야합니다.

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.onNext(parsedAccessToken!!)
바로 위의 clearTokens때문에 parsedAccessToken이 null이 되지않나요..?

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/build.gradle
> +    implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
RxJava만 있어도 될 것 같습니다.

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.onNext(parsedAccessToken!!)
emitter가 dispose되었다면 item을 emit하지 않아야 할 것 같습니다. (다른 부분도 확인 부탁드립니다.)

2018-07-20 07:55 UTC, kgwangrae commented on demoapp/src/main/kotlin/com/ridi/demoapp/MainActivity.kt
> +                Toast.makeText(this, "Error => $it", Toast.LENGTH_SHORT).show()
토스트는 보지 못하고 놓칠 수 있어서 로그도 동시에 기록되는 것이 좋을 것 같습니다.

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +    private fun clearTokens() {
파일에 저장된 토큰도 같이 지워야할 것 같습니다.

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
>          parsedAccessToken!!.expiresAt < Calendar.getInstance().timeInMillis / 1000
return type 생략이 가능합니다.

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +            assertEquals(it.expiresAt, 0)
0 보다는 `newExpiresAt` 같은 명칭이 붙어있으면 테스트 케이스의 의도가 더 명확해질 것 같습니다.

2018-07-20 07:55 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                        emitter.onError(ResponseCodeException("${response.code()}"))
로그인이 해제된 경우(로그인 페이지로 redirect되어 최종적으로는 reponse code가 200이 됨)와 그 외 오류를 구분할 수 없을 것 같습니다.

2018-07-20 09:23 UTC, RidiSangHoon commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +            assertEquals(it.expiresAt, 0)
`companion object`내에 `RIDI_AT_EXPIRES_AT_ZERO`와 함께 보았을때에는 0이 더 의도가 명확한것 같습니다.

2018-07-20 09:25 UTC, RidiSangHoon commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.onNext(parsedAccessToken!!)
말씀드린대로 `parsedAccessToken`이 null이 되면 `get()` 부분에서 다시 `parseAccessToken()`을 하기 때문에 관계 없을것 같습니다.

2018-07-31 10:40 UTC, RidiSangHoon commented
@kgwangrae 적용 완료하였습니다~! 리뷰 부탁드립니다.

2018-08-06 05:41 UTC, kgwangrae requested changes

2018-08-06 05:41 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                        .setHeader("Location", request.requestUrl)
다시 `ridi/authorize`로 redirect를 시키는 것인가요?

2018-08-06 05:41 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
>                      MockResponse().setResponseCode(HttpURLConnection.HTTP_OK)
바로 200을 주기 보다는 (가상의) 로그인 페이지 주소로 redirect 시키는 것이 좋을 것 같습니다.

2018-08-06 05:41 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/ApiManager.kt
> +    var cookieStorage = CookieStorage()
mutable하지 않아도 될 것 같습니다

2018-08-06 05:41 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/ApiManager.kt
> +    var service: ApiService? = null
- mutable하지 않아도 될 것 같습니다.
- nullable한가요?
- 현재 코드상으로는 backing field가 무의미한 상태인 것 같습니다.

2018-08-06 05:41 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        if (tokenFile != null && tokenFile!!.exists() && isDeletingTokenFileNeeded!!) {
마지막의 `!!`는 불필요합니다.

2018-08-06 05:41 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.onNext(parsedAccessToken!!)
이 코멘트에 대한 수정 사항이 없는 것 같습니다. (수정이 불필요하다고 판단하신 경우 답 comment 부탁드립니다.)

2018-08-06 05:41 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    }
`line 160~164`는 `line 166~179`에 적절히 합쳐질 수 있는 부분인 것 같습니다.

2018-08-06 06:00 UTC, RidiSangHoon commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                        .setHeader("Location", request.requestUrl)
넵 `isPriorResponseCalled`라는 변수를 통해 redirect가 됐는지를 표시하며, 해당 내용은 다시 `ridi/authorize`로 redirect시키는 것입니다.

2018-08-06 06:07 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                        .setHeader("Location", request.requestUrl)
변수명 `isPriorResponseCalled`의 의미가 다소 불분명하고, 더불어서 클라이언트에서 `ridi/authorize`를 요청했는데 다시 `ridi/authorize`로 redirect시키는 동작이 테스트에서 어떤 의미를 가지는지 궁금해서 질문을 드렸습니다.

2018-08-06 06:19 UTC, RidiSangHoon commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                        .setHeader("Location", request.requestUrl)
`TokenManager`내 `onResponse`에서는 `priorResponse`가 있어야합니다. 따라서, Test에서는 일부러 priorResponse를 만들어주는 작업을 다시 `ridi/authorize`로 redirect시키는 방법으로 구현하였습니다. 네이밍은 수정하겠습니다~!

2018-08-06 10:24 UTC, RidiSangHoon commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.onNext(parsedAccessToken!!)
d6059b3 커밋에서 수정했지만 처리가 부족했던것 같아 다시 커밋하였습니다~!

2018-08-06 10:43 UTC, RidiSangHoon commented
@kgwangrae 적용 완료하였습니다~

2018-08-07 09:09 UTC, kgwangrae requested changes

2018-08-07 09:09 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                        .setHeader("Location", APP_AUTHORIZED)
200인데 Location 헤더를 주는 것이 어색한 듯 합니다. 더불어서 이 case를 else로 처리하기보다는 위의 다른 case들과 같이 특정 URL로 요청이 들어온 경우에만 진입하도록 하는 것이 좋을 것 같습니다.

2018-08-07 09:09 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +                if (request.requestUrl.toString().contains(LOGIN_PAGE)) {
else if로 축약 가능할 것 같습니다.

2018-08-07 09:09 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    }
이전 코멘트에 대한 수정 사항이나 추가 코멘트가 없는 것 같습니다.

2018-08-07 09:09 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    if (emitter.isDisposed.not()) {
`getAccessToken`에는 여전히 dispose 체크가 없습니다.

2018-08-08 05:50 UTC, RidiSangHoon commented
@kgwangrae 적용 완료했습니다~!

2018-08-08 07:43 UTC, kgwangrae requested changes

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +            if (e.cause is UnexpectedRedirectUriException) {
다른 부분과 스타일이 통일되는 것이 좋을 것 같습니다. (여기서만 RuntimeException을 unwrapping해서 확인하고 있어서요)

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/CookieStorage.kt
> +                .dropLastWhile { it.isEmpty() }.toTypedArray()
Array로의 변환이 필요한가요?

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/EncryptionUtil.kt
> +    if (key == null) return this
코딩 컨벤션에 맞지 않는 부분인 것 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        internal fun JSONObject.parseCookie(cookieString: String) {
정확히는 쿠키를 parse해서 access / refresh token만을 취하는 함수이기 때문에 더 구체적인 이름을 가지는 것이 좋을 것 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +            apiManager.cookieStorage.tokenEncryptionKey = value
암호화 키 변경 시에 기존 토큰 파일을 지운다거나 새 키로 암호화하는 동작이 추가되어야 할 것 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        val savedToken = tokenFile!!.loadObject<String>() ?: throw FileNotFoundException()
불필요한 선언 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        val splitString = rawAccessToken!!.split("\\.".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
Array로 변환하지 않아도 무방할 것 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                            currentResponse.headers().values("Location")[0] == redirectUri) {
URI 비교 시에 단순 String으로 비교하면 `a.com/b/c`와 `a.com/b/c/`와 같이 slash나 parameter 유무 만으로도 동작이 달라질 수 있어서 적절히 normalize 후에 비교하는 것이 좋을 것 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.publishError(UnexpectedRedirectUriException("Response Code = ${response.code()}," +
불필요하게 message String으로 합쳐서 전달하는 것 보다는 `UnexpectedRedirectUriException(val responseCode: Int, val redirectedToUrl: String)` 이런 형태가 더 좋을 것 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +    private fun Call<ResponseBody>.requestUrlString() = this.request().url().toString()
이 부분의 3가지 Extension에 불필요한 `this`가 반복적으로 쓰여있습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +            this.onComplete()
`publishItem` 이라는 함수명에서 기대하기 어려운 동작 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +
불필요한 공백이 있습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +data class JWT(var subject: String, var userIndex: Int?, var expiresAt: Int)
`userIndex`가 nullable한가요?

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.publishError(UnexpectedRedirectUriException("Response Code = ${response.code()}," +
403이나 500 등의 에러도 여기서 처리되기 때문에, Exception의 명칭을 변경할 필요가 있을 것 같습니다.

2018-08-08 07:43 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +        val savedToken = tokenFile!!.loadObject<String>() ?: throw FileNotFoundException()
`tokenFile이 null인 것`과 `FileNotFound`는 의미에 다소 차이가 있는 것 같습니다.

2018-08-09 07:49 UTC, RidiSangHoon commented
@kgwangrae 코멘트 내용 적용하였습니다~

2018-08-09 08:59 UTC, kgwangrae commented on oauth2/src/androidTest/kotlin/com/ridi/oauth2/TokenManagerTest.kt
> +            if (e is IllegalStateException) {
IllegalStateException을 catch하는 것이 간결할 것 같습니다.

2018-08-09 08:59 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/EncryptionUtil.kt
>  private val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
별 문제가 없을 듯 하지만 https://stackoverflow.com/questions/6957406/is-cipher-thread-safe 링크를 참고 부탁드립니다.

2018-08-09 08:59 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +data class JWT(var subject: String, var userIndex: Int, var expiresAt: Int)
property들이 mutable type이어야 하나요?

2018-08-09 08:59 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +    private fun isTokenEncryptionKeyAvailable() = tokenEncryptionKey == null ||
`tokenEncryptionKey?.run { toByteArray(Charsets.UTF_8).count() == 16 } != false`도 좋을 것 같습니다.

2018-08-09 08:59 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +                    emitter.emitErrorIfNotDisposed(UnexpectedResponseException(response.code(),
넘겨주는 URL도 normalize 해주면 좋을 것 같습니다.

2018-08-09 09:36 UTC, kgwangrae commented
@RidiSangHoon repository description 및 README.md 내용 보강도 필요할 것 같습니다.

2018-08-09 10:31 UTC, kgwangrae requested changes

2018-08-09 10:31 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
>  class InvalidTokenFileException : Exception()
아래 두 Exception도 RuntimeException이면 좋을 것 같습니다.

2018-08-09 10:31 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +    private fun isTokenEncryptionKeyAvailable() = tokenEncryptionKey?.run {
암호화 key가 null인 경우도 허용하고 있어서 available보다는 다른 명칭이 좋을 것 같습니다.

2018-08-09 10:31 UTC, kgwangrae commented on oauth2/src/main/kotlin/com/ridi/oauth2/TokenManager.kt
> +data class JWT(val subject: String, val userIndex: Int, val expiresAt: Int)
`expiresAt: Int`는 단위가 불분명하므로 단위를 명시하거나 java.util.Date를 사용하는 것이 좋을 것 같습니다.

2018-08-10 05:50 UTC, kgwangrae approved these changes

2018-08-10 09:01 UTC, merged